[workspace]
resolver = "2"
members = [
    "mqttea-core",
    "mqttea-macros",
    "examples/asyncx"
]


[workspace.package]
edition = "2021"
keywords = ["mqtt", "network", "mqttea"]
categories = ["mqtt", "network"]
version = "0.1.0"
authors = [
    "Tolumide Shopein <tolumideshopein@gmail.com>"
]
