[package]
name = "mqttea"
version = "0.0.1"
edition = "2021"
authors = ["Tolumide Shopein <tolumideshopein@gmail.com>"]
description = "MQTT 5 client and server library in Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tolumide-ng/mqttea"


[dependencies]
